services:
  fastapi:
    build:
      context: .
    container_name: breast-cancer-api
    ports:
      - "8001:8000"

    environment:
          MLFLOW_TRACKING_URI: sqlite:///mlflow.db
          MLFLOW_ARTIFACTS_DIR: /app/mlartifacts
          MODEL_NAME: breast-cancer-classifier
          MODEL_ALIAS: champion

    volumes:
      - ./mlflow.db:/app/mlflow.db
      - ./mlartifacts:/app/mlartifacts
    networks:
      - mlops-network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - fastapi
    networks:
      - mlops-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - mlops-network
networks:
  mlops-network:
    driver: bridge
